---
title: "plan-demovate-revidert-2020"
author: "Sveinung Arnesen"
date: "6/5/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = " ", cache = FALSE, warning = FALSE)

setwd("C:\\Users/svein/Documents/DemovateR")

if(!require("broom")){install.packages("broom");  library(broom)}
if(!require("ggdag")){install.packages("ggdag");  library(ggdag)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("naniar")){install.packages("naniar");  library(naniar)}
if(!require("readxl")){install.packages("readxl");  library(readxl)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}

ggsave2 <- function(filename, ...) {
  for (format in c(".pdf", ".png")) ggsave(filename = paste0("output/", filename, format), ...)
}

  demovate <- read_xlsx("plan-forkommune-revidert-2020-b.xlsx")
```

# Milestones

```{r milestones}
options(knitr.kable.NA = " ")

table <- demovate %>%
  filter(!is.na(Milestone)) %>%
  dplyr::select(Year, Month, Action, WP)

kable(table, format = "html", booktabs = TRUE, caption = "Milestones") %>%  
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive") )  
```
```{r gantt}
#Gantt
gantt <- demovate %>% 
  filter(!is.na(Start_date)) %>% 
  pivot_longer(., Start_date:End_date, names_to = "period") %>% 
  mutate(value = as.Date(value, "%Y.%m.%d"),
         Action = as_factor(Action))  

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

plot1 <- ggplot(gantt, aes(x=value, y=fct_reorder(Action, desc(Item)), group=Item, color=as_factor(WP)))+
    geom_line(size = 7) +
  labs(x="Year", y=NULL, title="Project tasks, timeline") + 
  scale_colour_manual(values=cbbPalette) +
  labs(color = "Work package") +
     theme_light() +
  theme(axis.line.y=element_blank(),
                  axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                                  axis.line.x =element_blank(),
                 legend.position = "bottom"
                ) 
plot1

#Person-months by WP
#options(knitr.kable.NA = " ")

#df <- demovate %>% 
#  group_by(WP) %>% 
#  filter(!is.na(Researcher)) %>% 
#  summarise("Person-Months" = n())

#plot2 <- df %>% ggplot(aes(x=WP, y="Person-Months")) +
#  geom_bar() +
#  coord_flip() +
#  theme_classic()

#plot2
```

# Applied costs grouped by activity

```{r costs_wp}
options(knitr.kable.NA = " ")

table <- demovate %>%
  group_by(WP)%>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(table, format = "html", booktabs = TRUE, caption = "Total and applied costs, by work package", col.names = linebreak(c("WP", "Applied costs", "Total costs"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Total project costs by budget category
```{r costs_rcn_cat}
options(knitr.kable.NA = " ")

table <- demovate %>%
  group_by(RCN_cat)%>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(table, format = "html", booktabs = TRUE, caption = "Total and applied costs, by budget category", col.names = linebreak(c("Budget category", "Applied costs", "Total costs"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%
  row_spec(4, bold = T)

```

# Person-months by researcher category
```{r person_months}
options(knitr.kable.NA = " ")

table <- demovate %>%
  group_by(Researcher) %>%
  filter(!is.na(Researcher)) %>%
  summarise(n = n())

kable(table, format = "html", booktabs = TRUE, col.names = linebreak(c("Researcher", "Person-Months"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Person-months by year and research category
```{r person_months_year_rcn}
options(knitr.kable.NA = " ")

table <- demovate %>%
  group_by(Year, Researcher) %>%
  filter(!is.na(Researcher)) %>%
  summarise(months = n())

kable(table, format = "html", booktabs = TRUE, col.names = linebreak(c("Year", "Researcher", "Person-Months"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Person-months by year
```{r person_months_year}
options(knitr.kable.NA = " ")

table <- demovate %>%
  group_by(Year) %>%
  filter(!is.na(Researcher)) %>%
  summarise(n = n())

kable(table, format = "html", booktabs = TRUE, col.names = linebreak(c("Year", "Person-Months"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Person-months by work package
```{r person_months_wp}
options(knitr.kable.NA = " ")

df <- demovate %>%
  group_by(WP) %>%
  filter(!is.na(Researcher)) %>%
  summarise(n = n())

kable(df, format = "html", booktabs = TRUE, col.names = linebreak(c("WP", "Person-Months"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Cost per partner per year
```{r costs_partner}
options(knitr.kable.NA = " ")

df <- demovate %>%
  group_by(Institution, Year) %>%
  filter(!is.na(Institution)) %>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(df, format = "html", booktabs = TRUE, caption = "Total and applied costs, by year and partner", col.names = linebreak(c("Category", "Year", "Applied costs", "Total costs")))  %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Cost plan
```{r cost_plan}
options(knitr.kable.NA = " ")

df <- demovate %>%
  group_by(RCN_cat, Year) %>%
  filter(!is.na(Institution)) %>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(df, format = "html", booktabs = TRUE, caption = "Total and applied costs, by year and category", col.names = linebreak(c("Category", "Year", "Applied costs", "Total costs")))  %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```

# Allocations sought from the Research Council
```{r allocations}
options(knitr.kable.NA = " ")

df <- demovate %>%
  group_by(Researcher, Year) %>%
  filter(!is.na(Institution)) %>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(df, format = "html", booktabs = TRUE, caption = "Total and applied costs, by year and researcher", col.names = linebreak(c("Researcher", "Year", "Applied costs", "Total costs")))  %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))


```

# Total project costs by year
```{r costs_year}
options(knitr.table.NA = "")

table <- demovate %>%
  group_by(Year)%>%
  summarise(sum(Applied_costs, na.rm=TRUE),
            (sum(Project_costs, na.rm=TRUE)))
kable(table, format = "html", booktabs = TRUE, caption = "Total and applied costs, by year", col.names = linebreak(c("Year", "Applied costs", "Total costs"))) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```

# Full data set
```{r dataset}
options(knitr.kable.NA = " ")

table <- demovate %>%
  arrange(Year, Month)
  kable(table, format = "html", booktabs = TRUE, caption = "Total and applied costs, by budget category") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "responsive"), font_size = 15)

```
